### ISSUE TITLE
linting with standardjs

### ISSUE THREAD

**Issue by ninjatux** [withmethod/loop-and-crash#3]
What about removing any preference and simply stick with whatever is defined in the linting rules of [standardjs](https://standardjs.com/)?

There are many linters for any sort of text editor that are compliant with it and we remove any possible discussion about code style.

I also believe that to prevent errors the code linting should happen automatically before commit, as a git hook (that can be setup automatically after `npm i` by [`husky`](https://github.com/typicode/husky)), and before running the tests as a step of our current CI.

**Comment by thomaskrag** [comment]
Fixed in #5
